### ISSUE TITLE
[Feature]: Music Genre Filter

### ISSUE THREAD

**Issue by reneruano95** [reneruano95/intro-to-python-team-loyal-rebels#5]
**Description:**
Add a filter to display music based on genre.

- [ ] Add a genre filter dropdown or checkbox list to the frontend.
- [ ] Implement filtering logic in the backend to handle the selected genre.
- [ ] Ensure the frontend updates the displayed music list based on the selected genre.

**Additional Notes:**
Genre filter options available in the UI.
Filtering functionality works correctly, displaying music based on the selected genre.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added genre filter dropdown to the frontend, implemented genre filtering in the backend, and updated the UI to display filtered results.

You can review changes in this commit: https://github.com/lattaai13/reneruano95-intro-to-python-final-project-5/commit/b6b794cffb9f45812d924dc022826b49e19b5a77.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by reneruano95** [comment]
implemented with the advance search filters feature
